Renter/Renter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include(('users.urls', 'users'), namespace='users')),
]

Renter/core/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [

    path('', login_required(views.index), name='index'),
    path("building/<id>", login_required(views.building), name="building"),
    path('renter/<id>', login_required(views.renter), name='renter'),
    path('pending/<int:id>', login_required(views.pending), name='pending'),
    path('renter/pending/<int:id>', login_required(views.renter_pendings), name='renter_pending'),
    path('add-building', login_required(views.add_building), name='add-building'),
    path('edit-building/<int:id>', login_required(views.edit_building), name='edit-building'),
    path('delete-building/<int:id>', login_required(views.delete_building), name='delete-building'),
    path('add-room', login_required(views.add_room), name='add-room'),
    path('edit-room/<int:id>', login_required(views.edit_room), name='edit-room'),
    path('delete-room/<int:id>', login_required(views.delete_room), name='delete-room'),
    path('add-renter', login_required(views.add_renter), name='add-renter'),
    path('edit-renter/<int:id>', login_required(views.edit_renter), name='edit-renter'),
    path('delete-renter/<int:id>', login_required(views.delete_renter), name='delete-renter'),
    path('pay-rent/<int:id>', login_required(views.rent_pay), name='pay-rent'),
    path('edit-rent/<int:id>', login_required(views.edit_pay), name='edit-rent'),
    path('delete-rent/<int:id>', login_required(views.delete_rent), name='delete-rent'),
    path('bill/<int:id>', login_required(views.bill), name='bill'),
    path('building_mothly_total/<int:id>', login_required(views.building_mothly_total), name='building_mothly_total'),
    path('mothly_total/', login_required(views.monthly_total), name='mothly_total'),
]

Renter/users/general/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # redirect user based on authentication and authorisation
    path('', views.RedirectUserView.as_view(), name="redirect-user"),

    # user login
    path('login/', views.LoginView.as_view(), name='login'),
    # user logout
    path('logout/', views.LogoutView.as_view(), name='logout'),

    # user registration
    path('register/<str:key>/', views.RegisterView.as_view(), name='signup'),
    path('register/', views.RedirectUserView.as_view(), name='signup'),

    # user deletion
    # send confirmation mail
    path('delete/send-mail/', views.DeleteUserSendMail.as_view(), name='delete-send-mail'),
    # success message
    path('delete/send-mail/done/', views.MailSendDoneView.as_view(), name='delete-mail-done'),
    # delete confirmation page
    path('delete/confirm/', views.DeleteUserConfirmation.as_view(), name='delete-user-confirm'),
    # delete declined
    path('delete/decline/<token>', views.DeleteUseDecline.as_view(), name='delete-user-decline'),
    # delete confirmed
    path('delete/confirm/<token>/', views.DeleteUser.as_view(), name='delete-user'),

    # user update
    # change username
    path('username/<username>', views.ChangeUsername.as_view(), name='change-username'),
    # change fullname
    path('fullname/<username>', views.ChangeFullname.as_view(), name='change-fullname'),
    # change email
    path('email/<username>', views.ChangeEmail.as_view(), name='change-email'),

]

Renter/users/google_auth/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login/', views.GoogleLogin.as_view(), name='google-login'),
    path('login/callback/', views.GoogleCallback.as_view(), name='google-callback'),
    path('login/redirect/', views.GoogleRedirect.as_view(), name='google-redirect'),
]

Renter/users/reset_password/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # forgot password
    # two methods
    # using an url to reset password
    # path -
    # using otp to verify and redirect to reset password

    path('', views.GetEmailView.as_view(), name='password-forgot'),
    # redirect user to give their registered email and redirect to chosen path (otp/link)
    path('redirect/<token>/', views.RedirectUserView.as_view(), name='reset-password-redirect'),

    # forgot password link method
    # send an email with password reset link
    path('send-mail/link/<token>/', views.ResetSendLinkMail.as_view(), name='reset-send-link-mail'),
    # redirect user to a message page
    path('send-mail/done/<token>/', views.MailSendDoneView.as_view(), name='reset-mail-send-done'),

    # forgot password otp method
    # create an otp model
    path('create/otp/<token>/', views.ResetOTPCreateView.as_view(), name='reset-create-otp'),
    # send an email with an otp number
    path('send-mail/otp/<token>/', views.ResetSendOTPMail.as_view(), name='reset-send-otp-mail'),
    # verify otp
    path('verify-otp/<token>/', views.ResetVerifyOTP.as_view(), name='reset-otp-verify'),

    # common for both method
    # reset the password
    path('<uidb64>/<token>/', views.PasswordResetView.as_view(), name='reset-password'),
    # redirect the user
    path('done/', views.PasswordResetDoneView.as_view(), name='reset-password-done'),
]

Renter/users/urls.py
from django.urls import path, include

urlpatterns = [
    path("", include("users.general.urls")),
    path("password/forgot/", include("users.reset_password.urls")),
    path("password/change/", include("users.change_password.urls")),
    path("accounts/google/", include("users.google_auth.urls")),
]

Renter/users/change_password/forms.py
from django.contrib.auth.forms import PasswordChangeForm


class ChangePasswordForm(PasswordChangeForm):
    """
    Form for changing password
    this form uses old password to verify
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["old_password"].widget.attrs["placeholder"] = "Current Password"
        self.fields["new_password1"].widget.attrs["placeholder"] = "Password"
        self.fields["new_password2"].widget.attrs["placeholder"] = "Confirm Password"

Renter/users/django_mail/forms.py
from django import forms


class EmailForm(forms.Form):
    """
    Form with email field
    """
    email = forms.EmailField(widget=forms.TextInput(attrs={"autocomplete": "email", "placeholder": "Enter Your Email"}))

Renter/users/change_password/views.py
from django.contrib.auth import logout, get_user_model
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic, View

from users.django_mail import views as mail_views
from users.models import OTPModel
from users.otp import views as otp_views
from users.token import TokenValidationMixin, token_generator, PathTokenValidationMixin
from users.utils import generate_uidb64_url
from . import forms


class RedirectUserView(LoginRequiredMixin, generic.RedirectView):
    """
    redirect to send email to the user a password change link or a verification OTP
    otp = True will send an otp instead of link
    """
    otp = True

    def get_redirect_url(self, *args, **kwargs):
        token = token_generator.generate_token(user_id=self.request.user.id, path="change-redirect").make_token(
            self.request.user)
        if self.otp:
            return reverse_lazy("users:change-create-otp", kwargs={"token": token})
        return reverse_lazy("users:change-send-link-mail", kwargs={"token": token})


class ChangeSendMail(LoginRequiredMixin, PathTokenValidationMixin, mail_views.SendEmailView):
    """
    send password change email to user's email
    """
    template_name = "password-change/user-password-change-mail.html"
    email_subject = "Password Change Mail"
    send_html_email = True

    def get_to_email(self):
        return self.request.user.email


class ChangeSendLinkMail(ChangeSendMail):
    """
    send password change link to the user's email
    """
    pre_path = "change-redirect"
    email_template_name = "password-change/change-link-mail.html"

    def get_email_context_data(self):
        url = generate_uidb64_url(
            pattern_name="users:change-password",
            user=self.request.user,
            absolute=True,
            request=self.request
        )
        context = {"url": url}
        self.request.session["USER_EMAIL_ID"] = self.get_to_email()
        return context

    def get_success_url(self):
        token = token_generator.generate_token(user_id=self.request.user.id, path="mail-send").make_token(
            self.request.user)
        return reverse_lazy("users:change-mail-send-done", kwargs={"token": token})


class ChangeOTPCreateView(LoginRequiredMixin, PathTokenValidationMixin, View):
    pre_path = "change-redirect"

    def get_user_model(self):
        return self.request.user

    def get_success_url(self):
        token = token_generator.generate_token(user_id=self.request.user.id, path="otp-create").make_token(
            self.request.user)
        return reverse_lazy("users:change-send-otp-mail", kwargs={"token": token})

    def get(self, request, *args, **kwargs):
        user = self.get_user_model()
        otp = OTPModel(user=user, otp=otp_views.generate_otp())
        otp.save()
        request.session["OTP_ID"] = otp.id
        return redirect(self.get_success_url())


class ChangeSendOTPMail(ChangeSendMail):
    """
    send verification OTP to the users email
    """
    pre_path = "otp-create"
    email_template_name = "password-change/change-otp-mail.html"

    def get_email_context_data(self):
        otp_id = self.request.session.pop("OTP_ID")
        otp_model = OTPModel.objects.filter(id=otp_id).last()
        if not otp_model:
            return redirect(reverse_lazy("users:change-password-redirect"))
        return {"otp": otp_model.otp}

    def get_success_url(self):
        token = token_generator.generate_token(user_id=self.request.user.id, path="otp-send").make_token(
            self.request.user)
        return reverse_lazy("users:change-verify-otp", kwargs={"token": token})


class ChangeVerifyOTPView(LoginRequiredMixin, PathTokenValidationMixin, otp_views.VerifyOTPView):
    """
    verify the otp provided by the user
    """
    pre_path = "otp-send"
    template_name = "common/user-verify-otp.html"

    def get_user_model(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({"title": "Change Password"})
        return context

    def get_success_url(self):
        token_generator.delete_token(token=self.kwargs.get("token"))
        return generate_uidb64_url(pattern_name="users:change-password", user=self.get_user_model())


class MailSendDoneView(PathTokenValidationMixin, generic.TemplateView):
    """
    render a template after successfully sending email with success message
    """
    pre_path = "mail-send"
    template_name = "common/mail-send-done.html"

    def get_context_data(self, *args, **kwargs):
        email = self.request.session.pop("USER_EMAIL_ID")
        context = super().get_context_data()
        context.update({"email": email})
        return context


class PasswordChangeView(LoginRequiredMixin, TokenValidationMixin, auth_views.PasswordChangeView):
    """
    change password
    """
    form_class = forms.ChangePasswordForm
    template_name = "password-change/user-password-change.html"
    logout_user = True

    def verify_email(self):
        model = get_user_model().objects.get(id=self.request.user.id)
        model.email_verified = True
        model.save()

    def get_success_url(self):
        if not self.request.user.email_verified:
            self.verify_email()

        if self.logout_user:
            logout(self.request)

        return reverse_lazy("users:login")

Renter/users/django_mail/views.py
from django.core.exceptions import ImproperlyConfigured
from django.shortcuts import redirect
from django.views import generic, View

from users.mixins import FormMixin
from .forms import EmailForm
from .mixins import SendEmailMixin


class GetEmailView(FormMixin, generic.TemplateView):
    template_name = None
    form_class = EmailForm

    def form_valid(self, form):
        self.request.session['USER_EMAIL'] = form.cleaned_data['email']
        return redirect(self.get_success_url())


class SendEmailView(SendEmailMixin, View):
    """
    View to send email using django's smtp system
    """
    success_url = None

    def get_success_url(self):
        if self.success_url:
            return self.success_url
        raise ImproperlyConfigured(
            f"{self.__class__.__name__} missing 'success_url' attribute, define 'success_url' attribute or define "
            f"'get_success_url' method")

    def get(self, request, *args, **kwargs):
        self.send_mail()
        return redirect(self.get_success_url())

Renter/users/google_auth/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth import login
from django.contrib.auth.models import Group
from django.http import HttpResponseServerError
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View
from google_auth_oauthlib.flow import Flow
from googleapiclient.discovery import build
from django.core.exceptions import ImproperlyConfigured


def get_flow(state=None):
    return Flow.from_client_secrets_file(
        settings.GOOGLE_AUTH.get("client_secret_file"),
        scopes=settings.GOOGLE_AUTH.get("scopes"),
        redirect_uri=settings.GOOGLE_AUTH.get("redirect_uri"),
        state=state
    )


class GoogleLogin(View):

    def get(self, request):
        if not hasattr(settings, 'GOOGLE_AUTH'):
            raise ImproperlyConfigured("GOOGLE_AUTH is not configured")

        flow = get_flow()
        authorization_url, state = flow.authorization_url(
            access_type=settings.GOOGLE_AUTH.get("access_type"),
            prompt='select_account')
        request.session['GOOGLE_AUTH_STATE'] = state
        return redirect(authorization_url)


class GoogleCallback(View):

    def get_user_info(self):
        flow = get_flow(state=self.request.GET.get('GOOGLE_AUTH_STATE'))
        authorization_response = self.request.build_absolute_uri()
        flow.fetch_token(authorization_response=authorization_response)
        credentials = flow.credentials
        user_info_service = build('oauth2', 'v2', credentials=credentials)
        return user_info_service.userinfo().get().execute()

    def get(self, request, **kwargs):
        if request.GET.get('state') != request.session['GOOGLE_AUTH_STATE']:
            return HttpResponseServerError("Invalid google auth state")

        user_info = self.get_user_info()
        request.session['GOOGLE_AUTH_USER_INFO'] = user_info
        return redirect(reverse_lazy("users:google-redirect"))


class GoogleRedirect(View):
    model = get_user_model()
    template_name = 'general/user-login.html'
    group = None
    role = None
    redirect_url = None

    def user_exists(self, **kwargs):
        return self.model.objects.filter(**kwargs).exists()

    def get_user(self, **kwargs):
        return get_object_or_404(self.model, **kwargs)

    def get_redirect_url(self):
        if hasattr(settings, 'LOGIN_REDIRECT_URL'):
            return reverse_lazy(settings.LOGIN_REDIRECT_URL)

        if self.redirect_url:
            return reverse_lazy(self.redirect_url)

        raise ImproperlyConfigured("LOGIN_REDIRECT_URL is not configured")

    def login_user(self, user):
        login(self.request, user)
        return redirect(self.get_redirect_url())

    def get_default_group(self):
        if hasattr(settings, "DEFAULT_USER_GROUP_NAME"):
            return get_object_or_404(Group, name=settings.DEFAULT_USER_GROUP_NAME)

        if self.group:
            return get_object_or_404(Group, name=self.group)

        raise ImproperlyConfigured("DEFAULT_USER_GROUP_NAME is not configured")

    def get_default_role(self):
        user_model = get_user_model()
        if hasattr(settings, "DEFAULT_USER_GROUP_NAME"):
            return getattr(user_model, settings.DEFAULT_USER_ROLE)

        if self.group:
            return getattr(user_model, self.role)

        raise ImproperlyConfigured("DEFAULT_USER_GROUP_NAME is not configured")

    def add_role_and_group(self, user):
        user.role = self.get_default_role()
        user.groups.add(self.get_default_group())
        user.save()
        return self.login_user(user)

    @staticmethod
    def get_names(name):
        names = name.split()
        print(name, name)
        if len(names) == 1:
            return names[0], ""
        elif len(names) == 2:
            return names[0], names[1]

    def register_user(self, user_info):
        first_name, last_name = self.get_names(user_info.get("name"))
        data = {
            "email": user_info.get("email"),
            "username": user_info.get("email"),
            "first_name": first_name,
            "last_name": last_name,
        }
        user = get_user_model().objects.create_user(**data)
        return self.add_role_and_group(user)

    def get(self, request, **kwargs):
        user_info = request.session.pop('GOOGLE_AUTH_USER_INFO')
        if self.user_exists(email=user_info.get('email')):
            user = self.get_user(email=user_info.get("email"))
            return self.login_user(user)
        else:
            return self.register_user(user_info)

Renter/users/templates/general/user-delete-confirm.html
{% extends "common/user-base.html" %}
{% block title %} Delete Account {% endblock %}
{% block content %}
<div class="signinform">
    <h1>django-authentication</h1>
    <!-- container -->
    <div class="container">
        <!-- main content -->
        <div class="w3l-form-info">
            <div class="w3_info">
                <h2>Account Deletion confirmation</h2>
                <p>User - {{ user.username }}</p>
                <p>Email - {{ user.email }}</p>
                <a href="{{ delete_url }}"><button class="btn btn-primary btn-block" type="submit">Confirm</button></a>
                <a href="{{ decline_url }}"><button class="btn btn-primary btn-block" type="submit">Decline</button></a>
            </div>
        </div>
        <!-- //main content -->
    </div>
    <!-- //container -->
    <!-- footer -->
    <div class="footer">
        <p>&copy; 2020 Service login form. All Rights Reserved | Design by <a href="https://w3layouts.com/"
                target="blank">W3layouts</a></p>
    </div>
    <!-- footer -->
</div>
{% endblock %}

Renter/users/templates/general/user-delete-mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Reset</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h2 {
            color: #007bff;
        }
        p {
            color: #333;
        }
        .button {
            display: inline-block;
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
            margin-top: 15px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Account Deletion request</h2>
        <p>User - {{ user.username }}</p>
        <p>Email - {{ user.email }}</p>
		<a href="{{ url }}" class="button">Continue</a>
    </div>
</body>
</html>

Renter/users/templates/general/user-login.html
{% extends "common/user-base.html" %}
{% block title %} Login {% endblock %}
{% block content %}
<div class="signinform">
    <!-- container -->
    <div class="container">
        <!-- main content -->
        <div class="w3l-form-info">
            <div class="w3_info">
                <h2>Login</h2>
                <form method="post">
					{% csrf_token %}
                    {% include "common/user-form.html" with form=form %}
                    <div class="form-row bottom">
                    <div class="form-check">
                        <input type="checkbox" id="remenber" name="remenber" value="remenber">
                        <label for="remenber"> Remember me?</label>
                    </div>
					<a href="{% url 'users:password-forgot' %}" class="forgot">Forgot password?</a>
                    </div>
                    <button class="btn btn-primary btn-block" type="submit">Login</button>
                </form>
                <p class="continue"><span>or Login with</span></p>
                <div class="social-login">
                    <a href="{% url 'users:google-login' %}">
                        <div class="google">
                            <span class="fab fa-google" aria-hidden="true"></span>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <!-- //main content -->
    </div>
    <!-- //container -->
    {% include "common/footer.html" %}
</div>
{% endblock %}

Renter/users/templates/general/user-register.html
{% extends "common/user-base.html" %}
{% block title %} Register {% endblock %}
{% block content %}
<div class="signinform">
    <!-- container -->
    <div class="container">
        <!-- main content -->
        <div class="w3l-form-info">
            <div class="w3_info">
                <h2>Register</h2>
                <form method="post">
					{% csrf_token %}
                    {% include "common/user-form.html" with form=form %}
                    <button class="btn btn-primary btn-block" type="submit" id="btn-register">Register</button>
                </form>
                <p class="continue"><span>or register with</span></p>
                <div class="social-login">
                    <a href="#google">
                        <div class="google">
                            <span class="fab fa-google" aria-hidden="true"></span>
                        </div>
                    </a>
                </div>
				<p class="account">Already have an account? <a href="{% url 'users:login' %}">Login</a></p>
            </div>
        </div>
        <!-- //main content -->
    </div>
    <!-- //container -->
    {% include 'common/footer.html' %}
</div>
{% endblock %}
{% block scripts %}
    {% load static %}
	<script src="{% static "/js/validators/usernamevalidator.js" %}"></script>
	<script src="{% static "/js/validators/emailvalidator.js" %}"></script>
	<script src="{% static "/js/validators/passwordvalidator.js" %}"></script>
{% endblock %}

Renter/users/templates/general/user-update.html
{% extends "common/user-base.html" %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
<div class="signinform">
    <!-- container -->
    <div class="container">
        <!-- main content -->
        <div class="w3l-form-info">
            <div class="w3_info">
                <h2>{{ title }}</h2>
                <form method="post">
					{% csrf_token %}
                    {% include "common/user-form.html" with form=form %}
                    <button class="btn btn-primary btn-block" type="submit">Update</button>
                </form>
            </div>
        </div>
        <!-- //main content -->
    </div>
    <!-- //container -->
    {% include 'common/footer.html' %}
</div>
{% endblock %}